[package]
name = "service-benchmark"
version = "0.0.1"
authors = ["Eugene Retunsky"]
license = "MIT OR Apache-2.0"
edition = "2018"
publish = true
readme = "README.md"
repository = "https://github.com/xnuter/service-benchmark"
homepage = "https://github.com/xnuter/service-benchmark"
description = """
Benchmarking tool for network services.
"""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.10", features = ["rustls-tls"] }
clap = "3.0.0-beta.1"
derive_builder = "0.9"
log = "0.4"
log4rs = "1.0.0-alpha-1"
histogram = "0.6"
tokio = { version = "0.2", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_yaml = "0.8"
serde_json = "1.0"
leaky-bucket = "0.7"
async-trait = "0.1"

[dev-dependencies]
mockito = "0.27"
tokio-test = "0.2"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
